version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ColorSplashPhotoRetrieval"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1la0bps9l7q4o"
s3_prefix = "ColorSplashPhotoRetrieval"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
