AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ColorSplashPhotoRetrieval

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ColorSplashPhotoRetrieval:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 100
      Description: A Lambda that retrieve photos from the Unsplash API.
      FunctionName: ColorSplashPhotoRetrieval-Alpha
      Policies:
        - AWSLambdaBasicExecutionRole
