# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ColorSplashPhotoRetrieval

Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ColorSplashPhotoRetrieval:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 100
      Description: A Lambda function that returns a static string.
      FunctionName: ColorSplashPhotoRetrieval-Alpha
      Policies:
        - AWSLambdaBasicExecutionRole
